#mongodb:
#  host: "192.168.101.41"
#  port: 27017
#  database: "eland_data"
#  username: "admin"
#  password: "admin"
mongodb:
  host: "127.0.0.1"
  port: 27017
  database: "eland_data"
  username: "admin"
  password: "admin"
  collection-name: "test_aggregate"
# TODO CHECK
mysql:
  host: "192.168.101.41"
  port: 27017
  database: "eland_data"
  username: "admin"
  password: "admin"