#mongodb:
#  host: "192.168.101.41"
#  port: 27017
#  database: "eland_data"
#  username: "admin"
#  password: "admin"
mongodb:
  host: "127.0.0.1"
  port: 27017
  database: "eland_data"
  username: "admin"
  password: "admin"
  collection-name: "test_aggregate"

mysql:
  host: "localhost"
  port: 3306
  database: "id_mapping_db"
  username: "admin"
  password: "admin"
  table-name: "aggregate_table"

file-config:
  save-segment-folder-path: "./segment/"
